import type { ContentTypeMeta } from './types';

export const CONTENT_TYPE_REGISTRY: Record<string, ContentTypeMeta> = {
  epub: {
    label: 'epub',
    name: 'EPUB 電子書',
    nameEn: 'EPUB E-Book',
    mimeType: 'application/epub+zip',
    extensions: ['.epub'],
    category: 'ebook',
    description: '開放式電子書出版標準格式，包含 XHTML 內文與樣式',
    suggestedTools: [
      {
        name: 'EPUB 電子書編輯器',
        path: '/epub-editor',
        action: '使用 EPUB 編輯器開啟、排版與繁簡轉換',
      },
    ],
  },
  pdf: {
    label: 'pdf',
    name: 'PDF 文件',
    nameEn: 'PDF Document',
    mimeType: 'application/pdf',
    extensions: ['.pdf'],
    category: 'document',
    description: 'Adobe 便攜式文件格式，跨平台固定版面文件',
    suggestedTools: [
      {
        name: 'PDF 工具箱',
        path: '/pdf-tools',
        action: '合併、分割、旋轉或壓縮 PDF',
      },
      {
        name: 'PDF 數位簽名驗證',
        path: '/pdf-signature-checker',
        action: '檢查數位電子簽章有效性',
      },
    ],
  },
  txt: {
    label: 'txt',
    name: '純文字檔',
    nameEn: 'Plain Text',
    mimeType: 'text/plain',
    extensions: ['.txt', '.text'],
    category: 'text',
    description: '標準未格式化純文字編碼檔案',
    suggestedTools: [
      {
        name: 'TXT 轉 EPUB 電子書',
        path: '/txt-to-epub',
        action: '智慧辨識章節並製作為精美 EPUB 電子書',
      },
      {
        name: '繁簡轉換工具',
        path: '/tongwen-converter',
        action: '繁體中文與簡體中文批次轉換',
      },
    ],
  },
  markdown: {
    label: 'markdown',
    name: 'Markdown 文件',
    nameEn: 'Markdown Document',
    mimeType: 'text/markdown',
    extensions: ['.md', '.markdown'],
    category: 'document',
    description: '輕量級易讀易寫的標記語言文件',
    suggestedTools: [
      {
        name: 'Markdown 轉 HTML',
        path: '/markdown-to-html',
        action: '預覽並轉為標準 HTML 網頁',
      },
      {
        name: 'TXT 轉 EPUB 電子書',
        path: '/txt-to-epub',
        action: '將 Markdown 內容編譯為電子書',
      },
    ],
  },
  json: {
    label: 'json',
    name: 'JSON 資料檔',
    nameEn: 'JSON Data',
    mimeType: 'application/json',
    extensions: ['.json'],
    category: 'code',
    description: 'JavaScript 物件標記法資料交換格式',
    suggestedTools: [
      {
        name: 'JSON 檢視器',
        path: '/json-viewer',
        action: '結構化樹狀檢視與格式化',
      },
      {
        name: 'JSON 轉 YAML',
        path: '/json-to-yaml-converter',
        action: '轉換為 YAML 設定格式',
      },
      {
        name: 'JSON 轉 CSV',
        path: '/json-to-csv',
        action: '轉換為試算表 CSV 格式',
      },
    ],
  },
  csv: {
    label: 'csv',
    name: 'CSV 試算表',
    nameEn: 'CSV Spreadsheet',
    mimeType: 'text/csv',
    extensions: ['.csv'],
    category: 'database',
    description: '逗號分隔數值表格資料檔案',
    suggestedTools: [
      {
        name: 'CSV / Excel 檢視器',
        path: '/csv-excel-viewer',
        action: '在線上表格直接預覽與篩選 CSV',
      },
    ],
  },
  yaml: {
    label: 'yaml',
    name: 'YAML 設定檔',
    nameEn: 'YAML Configuration',
    mimeType: 'text/yaml',
    extensions: ['.yaml', '.yml'],
    category: 'code',
    description: '人性化可讀的資料序列化語言',
    suggestedTools: [
      {
        name: 'YAML 轉 JSON',
        path: '/yaml-to-json-converter',
        action: '將 YAML 轉換為 JSON 格式',
      },
    ],
  },
  xml: {
    label: 'xml',
    name: 'XML 標記文件',
    nameEn: 'XML Document',
    mimeType: 'application/xml',
    extensions: ['.xml'],
    category: 'code',
    description: '可擴記標記語言格式',
    suggestedTools: [
      {
        name: 'XML 轉 JSON',
        path: '/xml-to-json',
        action: '將 XML 結構解析轉換為 JSON',
      },
    ],
  },
  html: {
    label: 'html',
    name: 'HTML 網頁檔',
    nameEn: 'HTML Webpage',
    mimeType: 'text/html',
    extensions: ['.html', '.htm'],
    category: 'code',
    description: '超文本標記語言網頁文件',
    suggestedTools: [
      {
        name: 'HTML 所見即所得編輯器',
        path: '/html-wysiwyg-editor',
        action: '在富文本編輯器中即時檢視與修改',
      },
    ],
  },
  png: {
    label: 'png',
    name: 'PNG 影像',
    nameEn: 'PNG Image',
    mimeType: 'image/png',
    extensions: ['.png'],
    category: 'image',
    description: '可攜式網路圖形，支援無損壓縮與透明度',
    suggestedTools: [
      {
        name: '圖片壓縮',
        path: '/image-compression',
        action: '調整圖片品質與優化檔案大小',
      },
      {
        name: 'AI 圖片去背',
        path: '/remove-background',
        action: '使用本地 AI 自動移除主體背景',
      },
    ],
  },
  jpeg: {
    label: 'jpeg',
    name: 'JPEG 影像',
    nameEn: 'JPEG Image',
    mimeType: 'image/jpeg',
    extensions: ['.jpg', '.jpeg'],
    category: 'image',
    description: '常見有損壓縮數位照片標準格式',
    suggestedTools: [
      {
        name: '圖片壓縮',
        path: '/image-compression',
        action: '縮減 JPG 檔案大小',
      },
      {
        name: 'AI 圖片去背',
        path: '/remove-background',
        action: '辨識主體並去背',
      },
    ],
  },
  webp: {
    label: 'webp',
    name: 'WebP 影像',
    nameEn: 'WebP Image',
    mimeType: 'image/webp',
    extensions: ['.webp'],
    category: 'image',
    description: 'Google 開發之現代網頁高效影像格式',
    suggestedTools: [
      {
        name: '圖片壓縮',
        path: '/image-compression',
        action: '調整 WebP 畫質與體積',
      },
    ],
  },
  svg: {
    label: 'svg',
    name: 'SVG 向量圖',
    nameEn: 'SVG Vector Graphic',
    mimeType: 'image/svg+xml',
    extensions: ['.svg'],
    category: 'image',
    description: 'XML 基礎可縮放向量圖形',
    suggestedTools: [
      {
        name: 'SVG 工具箱',
        path: '/svg-tools',
        action: '預覽、最佳化與轉換 SVG 向量圖',
      },
    ],
  },
  gif: {
    label: 'gif',
    name: 'GIF 動態影像',
    nameEn: 'GIF Image',
    mimeType: 'image/gif',
    extensions: ['.gif'],
    category: 'image',
    description: '圖形交換格式，支援動畫效果',
  },
  bmp: {
    label: 'bmp',
    name: 'BMP 點陣圖',
    nameEn: 'Bitmap Image',
    mimeType: 'image/bmp',
    extensions: ['.bmp'],
    category: 'image',
    description: '未壓縮的點陣圖圖形檔案',
  },
  ico: {
    label: 'ico',
    name: 'ICO 圖示檔',
    nameEn: 'Icon File',
    mimeType: 'image/x-icon',
    extensions: ['.ico'],
    category: 'image',
    description: 'Windows 系統與網站 Favicon 圖示格式',
  },
  mp3: {
    label: 'mp3',
    name: 'MP3 音訊',
    nameEn: 'MP3 Audio',
    mimeType: 'audio/mpeg',
    extensions: ['.mp3'],
    category: 'audio',
    description: '普遍支援的高相容性壓縮音訊格式',
    suggestedTools: [
      {
        name: '音訊編輯器',
        path: '/audio-editor',
        action: '線上剪輯音訊並預覽音訊波形',
      },
    ],
  },
  wav: {
    label: 'wav',
    name: 'WAV 無損音訊',
    nameEn: 'WAV Audio',
    mimeType: 'audio/wav',
    extensions: ['.wav'],
    category: 'audio',
    description: '未壓縮的高品質標準音訊檔',
    suggestedTools: [
      {
        name: '音訊編輯器',
        path: '/audio-editor',
        action: '剪輯與編輯 WAV 錄音檔',
      },
    ],
  },
  ogg: {
    label: 'ogg',
    name: 'OGG 音訊',
    nameEn: 'OGG Audio',
    mimeType: 'audio/ogg',
    extensions: ['.ogg', '.oga'],
    category: 'audio',
    description: '開放式開源音訊容器格式',
    suggestedTools: [
      {
        name: '音訊編輯器',
        path: '/audio-editor',
        action: '剪輯 OGG 音訊檔',
      },
    ],
  },
  flac: {
    label: 'flac',
    name: 'FLAC 無損音訊',
    nameEn: 'FLAC Audio',
    mimeType: 'audio/flac',
    extensions: ['.flac'],
    category: 'audio',
    description: '免費無損音訊壓縮編碼格式',
  },
  mp4: {
    label: 'mp4',
    name: 'MP4 影片',
    nameEn: 'MP4 Video',
    mimeType: 'video/mp4',
    extensions: ['.mp4'],
    category: 'video',
    description: 'MPEG-4 Part 14 標準數位多媒體容器',
  },
  webm: {
    label: 'webm',
    name: 'WebM 影音檔',
    nameEn: 'WebM Video',
    mimeType: 'video/webm',
    extensions: ['.webm'],
    category: 'video',
    description: '專為網頁設計之開放多媒體格式',
  },
  mkv: {
    label: 'mkv',
    name: 'Matroska 影音檔',
    nameEn: 'MKV Video',
    mimeType: 'video/x-matroska',
    extensions: ['.mkv'],
    category: 'video',
    description: '可包含多音軌與字幕的高彈性影音容器',
  },
  zip: {
    label: 'zip',
    name: 'ZIP 壓縮封裝檔',
    nameEn: 'ZIP Archive',
    mimeType: 'application/zip',
    extensions: ['.zip'],
    category: 'archive',
    description: '普遍使用的無損資料壓縮封裝格式',
  },
  sevenzip: {
    label: 'sevenzip',
    name: '7-Zip 壓縮檔',
    nameEn: '7z Archive',
    mimeType: 'application/x-7z-compressed',
    extensions: ['.7z'],
    category: 'archive',
    description: '高壓縮比的開放架構壓縮檔案',
  },
  tar: {
    label: 'tar',
    name: 'TAR 打包檔',
    nameEn: 'TAR Archive',
    mimeType: 'application/x-tar',
    extensions: ['.tar'],
    category: 'archive',
    description: 'Unix 磁帶封存打包格式',
  },
  gzip: {
    label: 'gzip',
    name: 'GZIP 壓縮檔',
    nameEn: 'GZIP Compressed File',
    mimeType: 'application/gzip',
    extensions: ['.gz'],
    category: 'archive',
    description: 'GNU 專用高效壓縮檔案',
  },
  rar: {
    label: 'rar',
    name: 'RAR 壓縮檔',
    nameEn: 'RAR Archive',
    mimeType: 'application/vnd.rar',
    extensions: ['.rar'],
    category: 'archive',
    description: 'Roshal Archive 專有壓縮格式',
  },
  docx: {
    label: 'docx',
    name: 'Word 文件',
    nameEn: 'Microsoft Word Document',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    extensions: ['.docx'],
    category: 'document',
    description: 'Office Open XML 標準文書處理文件',
  },
  xlsx: {
    label: 'xlsx',
    name: 'Excel 試算表',
    nameEn: 'Microsoft Excel Spreadsheet',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    extensions: ['.xlsx'],
    category: 'document',
    description: 'Office Open XML 標準試算表',
    suggestedTools: [
      {
        name: 'CSV / Excel 檢視器',
        path: '/csv-excel-viewer',
        action: '在線上檢視工作表內容',
      },
    ],
  },
  pptx: {
    label: 'pptx',
    name: 'PowerPoint 簡報',
    nameEn: 'Microsoft PowerPoint',
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    extensions: ['.pptx'],
    category: 'document',
    description: 'Office Open XML 標準簡報文件',
  },
  apk: {
    label: 'apk',
    name: 'Android 應用程式包',
    nameEn: 'Android APK',
    mimeType: 'application/vnd.android.package-archive',
    extensions: ['.apk'],
    category: 'archive',
    description: 'Android 作業系統應用程式封裝套件',
  },
  ipa: {
    label: 'ipa',
    name: 'iOS 應用程式包',
    nameEn: 'iOS App IPA',
    mimeType: 'application/x-itunes-ipa',
    extensions: ['.ipa'],
    category: 'archive',
    description: 'Apple iOS 應用程式封裝套件',
  },
  javascript: {
    label: 'javascript',
    name: 'JavaScript 原始碼',
    nameEn: 'JavaScript Source',
    mimeType: 'application/javascript',
    extensions: ['.js', '.mjs', '.cjs'],
    category: 'code',
    description: '網頁客戶端與 Node.js 腳本語言原始碼',
  },
  typescript: {
    label: 'typescript',
    name: 'TypeScript 原始碼',
    nameEn: 'TypeScript Source',
    mimeType: 'application/typescript',
    extensions: ['.ts', '.mts', '.cts'],
    category: 'code',
    description: '具備靜態型別定義之 JavaScript 超集',
  },
  python: {
    label: 'python',
    name: 'Python 原始碼',
    nameEn: 'Python Source',
    mimeType: 'text/x-python',
    extensions: ['.py'],
    category: 'code',
    description: '高階直譯式程式語言原始碼',
  },
  rust: {
    label: 'rust',
    name: 'Rust 原始碼',
    nameEn: 'Rust Source',
    mimeType: 'text/x-rust',
    extensions: ['.rs'],
    category: 'code',
    description: '著重記憶體安全與高並發之系統級程式語言',
  },
  go: {
    label: 'go',
    name: 'Go 原始碼',
    nameEn: 'Go Source',
    mimeType: 'text/x-go',
    extensions: ['.go'],
    category: 'code',
    description: 'Google 開發之靜態編譯型高效率語言',
  },
  c: {
    label: 'c',
    name: 'C 語言原始碼',
    nameEn: 'C Source Code',
    mimeType: 'text/x-c',
    extensions: ['.c', '.h'],
    category: 'code',
    description: '經典結構化系統級通用程式語言',
  },
  cpp: {
    label: 'cpp',
    name: 'C++ 原始碼',
    nameEn: 'C++ Source Code',
    mimeType: 'text/x-c++',
    extensions: ['.cpp', '.cc', '.cxx', '.hpp'],
    category: 'code',
    description: '支援物件導向與泛型之高效能程式語言',
  },
  java: {
    label: 'java',
    name: 'Java 原始碼',
    nameEn: 'Java Source Code',
    mimeType: 'text/x-java-source',
    extensions: ['.java'],
    category: 'code',
    description: '跨平台物件導向程式語言原始碼',
  },
  sql: {
    label: 'sql',
    name: 'SQL 查詢腳本',
    nameEn: 'SQL Script',
    mimeType: 'application/sql',
    extensions: ['.sql'],
    category: 'database',
    description: '結構化查詢語言關聯式資料庫腳本',
  },
  sqlite: {
    label: 'sqlite',
    name: 'SQLite 資料庫',
    nameEn: 'SQLite Database',
    mimeType: 'application/vnd.sqlite3',
    extensions: ['.sqlite', '.db', '.sqlite3'],
    category: 'database',
    description: '輕量型嵌入式無伺服器關聯式資料庫檔案',
  },
  wasm: {
    label: 'wasm',
    name: 'WebAssembly 二進位模組',
    nameEn: 'WebAssembly Binary',
    mimeType: 'application/wasm',
    extensions: ['.wasm'],
    category: 'binary',
    description: '在現代瀏覽器與伺服器高效執行的堆疊虛擬機二進位代碼',
  },
  pebin: {
    label: 'pebin',
    name: 'Windows PE 可執行檔',
    nameEn: 'Windows Portable Executable (EXE/DLL)',
    mimeType: 'application/x-dosexec',
    extensions: ['.exe', '.dll', '.sys'],
    category: 'executable',
    description: 'Windows 平台標準可執行檔或動態連結程式庫',
  },
  elf: {
    label: 'elf',
    name: 'Linux ELF 可執行檔',
    nameEn: 'Linux Executable and Linkable Format',
    mimeType: 'application/x-executable',
    extensions: ['.elf', '.so', ''],
    category: 'executable',
    description: 'Linux / Unix 系統標準二進位執行檔或共享函式庫',
  },
  macho: {
    label: 'macho',
    name: 'macOS Mach-O 可執行檔',
    nameEn: 'macOS Mach-O Binary',
    mimeType: 'application/x-mach-binary',
    extensions: ['.dylib', ''],
    category: 'executable',
    description: 'Apple Darwin / macOS / iOS 系統二進位執行檔架構',
  },
  dockerfile: {
    label: 'dockerfile',
    name: 'Dockerfile 建置檔',
    nameEn: 'Dockerfile',
    mimeType: 'text/x-dockerfile',
    extensions: ['Dockerfile', '.dockerfile'],
    category: 'code',
    description: 'Docker 容器映像檔自動化構建腳本',
  },
  shell: {
    label: 'shell',
    name: 'Shell 命令腳本',
    nameEn: 'Shell Script',
    mimeType: 'application/x-sh',
    extensions: ['.sh', '.bash', '.zsh'],
    category: 'code',
    description: 'Unix / Linux 命令直譯器腳本',
  },
  batch: {
    label: 'batch',
    name: 'Windows 批次檔',
    nameEn: 'Windows Batch File',
    mimeType: 'application/x-bat',
    extensions: ['.bat', '.cmd'],
    category: 'code',
    description: 'Windows 命令提示字元批次腳本',
  },
  powershell: {
    label: 'powershell',
    name: 'PowerShell 腳本',
    nameEn: 'PowerShell Script',
    mimeType: 'application/x-powershell',
    extensions: ['.ps1'],
    category: 'code',
    description: 'Windows / 跨平台進階系統管理自動化腳本',
  },
  empty: {
    label: 'empty',
    name: '空白空檔案',
    nameEn: 'Empty File',
    mimeType: 'application/x-empty',
    extensions: [],
    category: 'unknown',
    description: '內容為 0 位元組的空檔案',
  },
  unknown: {
    label: 'unknown',
    name: '未知二進位檔案',
    nameEn: 'Unknown Binary',
    mimeType: 'application/octet-stream',
    extensions: ['.bin'],
    category: 'binary',
    description: '未符合特定特徵簽名的二進位資料',
  },
};

export function getMetaForLabel(label: string): ContentTypeMeta {
  if (CONTENT_TYPE_REGISTRY[label]) {
    return CONTENT_TYPE_REGISTRY[label];
  }

  return {
    label,
    name: label.toUpperCase(),
    nameEn: label.toUpperCase(),
    mimeType: `application/x-${label}`,
    extensions: [`.${label}`],
    category: 'unknown',
    description: `Google Magika 辨識之內容類型標籤：${label}`,
  };
}
